GET http://localhost:3001/users HTTP/1.1

###
GET http://localhost:3001/users/ugGzUr2YCeSqHi5BsAepcpg8ISw1 HTTP/1.1

###
POST http://localhost:3001/users/post HTTP/1.1
content-type: application/json

{
    "fname": "sample2",
    "lname": "testLast2",
    "uid": "sdfgfg"
}