GET http://localhost:3001/users HTTP/1.1

###
GET http://localhost:3001/users/ugGzUr2YCeSqHi5BsAepcpg8ISw1 HTTP/1.1

###
POST http://localhost:3001/users/post HTTP/1.1
content-type: application/json

{
    "fname": "sample2",
    "lname": "testLast2",
    "uid": "sdfgfg"
}

###
GET http://localhost:3001/polls/6090df6d78803c1ceb8a8a96 HTTP/1.1

###
GET http://localhost:3001/polls/pollnames/OIJn0idMXLPtmg5iGWTur5j62o32 HTTP/1.1


###
POST http://localhost:3001/polls/post HTTP/1.1
content-type: application/json

{
   "pollName": "testPoll3",
  "details": "test details",
  "rsvpDate": "2021-4-16",
  "pollType": ["r1234", "3"],
  "authId": "test"
}

###
PATCH http://localhost:3001/polls/upd/608e1a61c0e66004e64d174f HTTP/1.1
Accept: {application/json}
Content-Type: application/json

{
  "pollOptions": [
    {"pollType": 1,
    "pollId": "fdsd2324",
    "option": "test patch"}
  ]
}