GET http://localhost:3001/users HTTP/1.1

###
GET http://localhost:3001/users/ugGzUr2YCeSqHi5BsAepcpg8ISw1 HTTP/1.1

###
POST http://localhost:3001/users/post HTTP/1.1
content-type: application/json

{
    "fname": "sample2",
    "lname": "testLast2",
    "uid": "sdfgfg"
}

###
GET http://localhost:3001/polls/ HTTP/1.1


###
POST http://localhost:3001/polls/post HTTP/1.1
content-type: application/json

{
   "pollName": "testPoll3",
  "details": "test details",
  "rsvpDate": "2021-4-16",
  "pollType": ["r1234", "3"],
  "authId": "test"
}